- name: Install rust
  command: >
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  when: false

# - name: Install rust-analyzer
#   command: >
#     mkdir -p ~/.local/bin &&
#     curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer &&
#     chmod +x ~/.local/bin/rust-analyzer
