- name: set up pi
  hosts: homelab
  roles:
    - role: vim
      tags:
        - vim
    - role: pihole
      tags:
        - pihole
    - role: monitoring
      tags:
        - monitoring
    - role: traefik
      tags:
        - traefik
    - role: portainer
      tags:
        - portainer
