- name: Install ripgrep
  ansible.builtin.command: cargo install ripgrep

- name: Install fd
  ansible.builtin.command: cargo install fd-find

- name: Install less
  ansible.builtin.package:
    name: less
    state: present

- name: Ensure /usr/local/bin directory exists
  become: true
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Copy binaries
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - "tat"
    - "tmux-sessionizer"
