- name: Install ripgrep
  become: true
  ansible.builtin.package: 
    name: ripgrep
    state: present


- name: Install fd
  become: true
  ansible.builtin.package: 
    name: fd-find
    state: present

- name: Install less
  become: true
  ansible.builtin.package:
    name: less
    state: present

- name: Create local bin
  file:
    path: "{{ dotfiles_user_home }}/.local/bin"
    state: directory
    mode: "0755"

- name: Symlink bin files
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/system-packages/files/{{ item }}"
    dest: "{{ dotfiles_user_home }}/.local/bin/{{ item }}"
    state: link
  with_items:
    - "tat"
    - "tmux-sessionizer"
