- name: Install ripgrep
  ansible.builtin.command: cargo install ripgrep

- name: Install fd
  ansible.builtin.command: cargo install fd-find

- name: Install less
  ansible.builtin.package:
    name: less
    state: present
