- name: Only run Aerospace role on macOS
  ansible.builtin.meta: end_play
  when: ansible_facts['os_family'] != 'Darwin'

- name: Ensure Aerospace is installed via Homebrew
  community.general.homebrew:
    name: aerospace
    state: present

- name: Ensure Aerospace config directory exists
  file:
    path: "{{ aerospace_home_config }}"
    state: directory
    mode: "0755"

- name: Symlink Aerospace config
  file:
    src: "{{ role_path }}/files/aerospace.toml"
    dest: "{{ aerospace_home_config }}/aerospace.toml"
    state: link
