- name: Install oh-my-zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ home }}/.oh-my-zsh"

- name: Clone zsh plugins (only if missing, no updates)
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    clone: true
    update: false
  loop: "{{ oh_my_zsh_plugins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install starship
  community.general.homebrew:
    name: starship
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Check which zsh config files exist
  ansible.builtin.stat:
    path: "{{ home }}/{{ item }}"
  loop: "{{ zsh_config_files }}"
  register: zsh_stat_files

- name: Back up existing zsh config files
  command: mv "{{ home }}/{{ item.item }}" "{{ home }}/{{ item.item }}.bak"
  args:
    creates: "{{ home }}/{{ item.item }}.bak"
  when: item.stat.exists
  loop: "{{ zsh_stat_files.results }}"

- name: Symlink zsh config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
    force: true
  loop: "{{ zsh_config_files }}"
