live_config_reload: true

window:
  dynamic_padding: false
  decorations: full
  startup_mode: Maximized
  title: Alacritty
  dynamic_title: true

key_bindings:
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Key3, mods: Control, chars: "\x1b" }
  - { key: Key4, mods: Control, chars: "\x1c" }
  - { key: Key5, mods: Control, chars: "\x1d" }
  - { key: Key6, mods: Control, chars: "\x1e" }
  - { Key: H, mods: Control|Alt, chars: "\x1b\x08" }
  - { Key: J, mods: Control|Alt, chars: "\x1b\x0a" }
  - { Key: K, mods: Control|Alt, chars: "\x1b\x0b" }
  - { Key: L, mods: Control|Alt, chars: "\x1b\x0c" }
  - { Key: D, mods: Control|Alt, chars: "\x1b\x04" }
  - { Key: P, mods: Control|Alt, chars: "\x1b\x10" }
  # MacOs
  - { Key: H, mods: Alt, chars: "\x1bh" }
  - { Key: J, mods: Alt, chars: "\x1bj" }
  - { Key: K, mods: Alt, chars: "\x1bk" }
  - { Key: L, mods: Alt, chars: "\x1bl" }
  - { Key: F, mods: Alt, chars: "\x1bf" }
  - { Key: D, mods: Alt, chars: "\x1bd" }
  - { Key: B, mods: Alt, chars: "\x1bb" }
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic

  size: 14.0

# The definition of color schemes.
schemes:
  catpuccin: &catpuccin # Default colors
    primary:
      background: "0x1E1D2F"
      foreground: "0xD9E0EE"

    # Colors the cursor will use if `custom_cursor_colors` is true

    cursor:
      text: "0x1E1D2F"
      cursor: "0xF5E0DC"

    # Normal colors
    normal:
      black: "0x6E6C7E"
      red: "0xF28FAD"
      green: "0xABE9B3"
      yellow: "0xFAE3B0"
      blue: "0x96CDFB"
      magenta: "0xF5C2E7"
      cyan: "0x89DCEB"
      white: "0xD9E0EE"

    # Bright colors
    bright:
      black: "0x988BA2"

      red: "0xF28FAD"
      green: "0xABE9B3"
      yellow: "0xFAE3B0"
      blue: "0x96CDFB"
      magenta: "0xF5C2E7"
      cyan: "0x89DCEB"
      white: "0xD9E0EE"

    indexed_colors:
      - { index: 16, color: "0xF8BD96" }
      - { index: 17, color: "0xF5E0DC" }

# Apply the color scheme.
colors: *catpuccin
