---
live_config_reload: true

window:
  dynamic_padding: false
  decorations: full
  startup_mode: Maximized
  title: Alacritty
  dynamic_title: false

key_bindings:
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Key3, mods: Control, chars: "\x1b" }
  - { key: Key4, mods: Control, chars: "\x1c" }
  - { key: Key5, mods: Control, chars: "\x1d" }
  - { key: Key6, mods: Control, chars: "\x1e" }
  - { Key: H, mods: Control|Alt, chars: "\x1b\x08" }
  - { Key: J, mods: Control|Alt, chars: "\x1b\x0a" }
  - { Key: K, mods: Control|Alt, chars: "\x1b\x0b" }
  - { Key: L, mods: Control|Alt, chars: "\x1b\x0c" }
  - { Key: D, mods: Control|Alt, chars: "\x1b\x04" }
  - { Key: P, mods: Control|Alt, chars: "\x1b\x10" }
  # MacOs
  - { Key: H, mods: Alt, chars: "\x1bh" }
  - { Key: J, mods: Alt, chars: "\x1bj" }
  - { Key: K, mods: Alt, chars: "\x1bk" }
  - { Key: L, mods: Alt, chars: "\x1bl" }
  - { Key: F, mods: Alt, chars: "\x1bf" }
  - { Key: D, mods: Alt|Shift, chars: "\x1bd" }
  - { Key: B, mods: Alt, chars: "\x1bb" }
  - { Key: Q, mods: Control, chars: "\x11" }
  - { Key: P, mods: Alt|Shift|Control, chars: "\x1bp" }
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word
  - { key: LBracket, mods: Alt, chars: "\x1b[" }
  - { key: RBracket, mods: Alt, chars: "\x1b]" }

draw_bold_text_with_bright_colors: true

font:
  size: 18.0
  offset:
    y: -4 # Match it closer to macOs default vertical spacing
  normal:
    family: MesloLGS Nerd Font Mono
    style: Regular
  bold:
    family: MesloLGS Nerd Font Mono
    style: Bold
  italic:
    family: MesloLGS Nerd Font Mono
    style: Regular Italic
  bold_italic:
    family: MesloLGS Nerd Font Mono
    style: Bold Italic
