- name: Install fzf on macOS
  ansible.builtin.package:
    name: fzf
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install fzf on Debian-based Linux (Ubuntu/WSL)
  ansible.builtin.apt:
    name: fzf
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'
  become: true

- name: Run fzf install script (macOS Homebrew)
  ansible.builtin.command:
    cmd: /opt/homebrew/opt/fzf/install --key-bindings --completion --no-update-rc
  when: ansible_facts['os_family'] == 'Darwin'
