- name: Install fzf
  ansible.builtin.package:
    name: fzf
    state: present

- name: Install fzf config
  ansible.builtin.command:
    cmd: "/opt/homebrew/opt/fzf/install"
    creates: "{{ home }}/.fzf"
