- name: Create git config directory
  file:
    path: "{{ home }}/.config/git"
    state: directory
    mode: "0755"

- name: Symlink git config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ home_config }}/git/config"
    state: link
    force: yes

- name: Install git delta
  ansible.builtin.command:
    cmd: cargo install git-delta
