- name: Create git config directory
  file:
    path: "{{ home }}/.config/git"
    state: directory
    mode: "0755"

- name: Symlink git config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ home_config }}/git/{{ item }}"
    state: link
    force: true
  with_items:
    - "config"
    - "config-po"

- name: Install git delta
  ansible.builtin.command:
    cmd: cargo install git-delta
