- name: Create git config directory
  file:
    path: "{{ dotfiles_user_home }}/.config/git"
    state: directory
    mode: "0755"

- name: Symlink git config
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/git/files/config"
    dest: "{{ dotfiles_user_home }}/.config/git/config"
    state: link
    force: yes

- name: Install git delta
  ansible.builtin.command:
    cmd: cargo install git-delta
