#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    path_name=$1
else
    path_name=$(find ~ ~/projects ~/personal ~/git -mindepth 1 -maxdepth 1 -type d 2>/dev/null | fzf)
fi

if [[ -z $path_name ]]; then
    exit 0
fi

selected_name=$(basename "$path_name" | tr . _)
tmux_running=$(pgrep tmux)

tat $selected_name $path_name
