- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  ignore_errors: true

- name: Create tmux plugins directory
  file:
    path: "{{ home }}/.tmux/plugins"
    state: directory
    mode: "0755"

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{home}}/.tmux/plugins/tpm"
  ignore_errors: true

- name: Symlink tmux config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    state: link
