- name: install docker
  include_role: 
    name: geerlingguy.docker
  vars:
    docker_users:
      - homelab

- name: install host machine docker plugin
  become: yes
  ansible.builtin.apt:
    name: python3-docker
    state: present
