# dnsmasq:
#   customDnsEntries:
#     - address=/nas/192.168.178.10
#
#   customCnameEntries:
#     - cname=foo.nas,nas

persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.1.34
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  ingress:
    enabled: true

serviceDns:
  loadBalancerIP: 192.168.1.34
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
