- name: "Repo PHP"
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: "Install PHP"
  ansible.builtin.apt:
    name: php8.1
    state: present
  become: true

- name: "Install PHP extensions"
  ansible.builtin.apt:
    pkg:
      - php8.1-imagick
      - php8.1-redis
      - php8.1-xdebug
  become: true
