- import_tasks: Darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- import_tasks: Debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Check for phpcs config dir
  ansible.builtin.stat: 
    path: "{{ dotfiles_user_home }}/.config/phpcs"
  register: phpcs_config_stat

- name: Create phpcs config dir
  file:
    path: "{{ dotfiles_user_home }}/.config/phpcs"
    state: directory
    mode: "0755"
  when: not phpcs_config_stat.stat.exists
  
  
- name: Symlink php cs fixer config
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/php/files/.php-cs-fixer.php"
    dest: "{{ dotfiles_user_home }}/.config/phpcs/.php-cs-fixer.php"
    state: link
    force: yes
  when: not phpcs_config_stat.stat.exists
