- name: Create alacritty config dir
  ansible.builtin.file:
    path: "{{ home }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Install alacritty
  ansible.builtin.package:
    name: alacritty
    state: present
  ignore_errors: true

- name: Link alacritty.toml config file
  ansible.builtin.file:
    src: "{{ home_dotfiles }}/roles/alacritty/files/alacritty.toml"
    dest: "{{ home }}/.config/alacritty/alacritty.toml"
    state: link
