- name: Create alacritty config dir
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Install alacritty
  ansible.builtin.package:
    name: alacritty
    state: present
  ignore_errors: true

- name: Link alacritty.yml config file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/alacritty/files/alacritty.{{ ansible_facts['os_family'] }}.yml"
    dest: "{{ dotfiles_user_home }}/.config/alacritty/alacritty.yml"
    state: link
