- name: Install eslint and json lsp
  community.general.npm:
    name: vscode-langservers-extracted
    global: true

- name: Install intelephense lsp
  community.general.npm:
    name: intelephense
    global: true

- name: Create intelephense licence folder
  ansible.builtin.file:
    path: "{{dotfiles_user_home}}/intelephense"
    state: directory

- name: Create intelephense licence file
  ansible.builtin.file:
    path: "{{dotfiles_user_home}}/intelephense/licence.txt"
    state: touch

- name: Install styleline lsp
  community.general.npm:
    name: stylelint-lsp
    global: true

- name: Install ts lsp
  community.general.npm:
    name: typescript-language-server
    global: true

- name: Install yaml lsp
  community.general.npm:
    name: yaml-language-server
    global: true

- name: Install ansible lsp
  community.general.npm:
    name: '@ansible/ansible-language-server'
    global: true

- import_tasks: sumneko_lua.yml
