- import_tasks: mac.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Clone nvim config
  ansible.builtin.git:
    repo: 'git@github.com:marwan38/nvim_config'
    dest: "{{ git_dir }}/nvim_config"
    update: false

- name: Sym link nvim dir
  ansible.builtin.file:
    src: "{{ git_dir }}/nvim_config"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
