- import_tasks: mac.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Clone nvim config
  ansible.builtin.git:
    repo: 'git@github.com:marwan38/sindrets-dotfiles.git'
    dest: "{{ sindrets_dotfiles }}"
    update: false

- name: Sym link nvim dir
  ansible.builtin.file:
    src: "{{ git_dir }}/sindrets-dotfiles/.config/nvim"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link

- name: Clone packer.nvim (plugin manager)
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ dotfiles_user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Install plugins
  ansible.builtin.command: 
    cmd: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  when: false
