- name: "pihole docker network"
  community.docker.docker_network:
    name: pihole
    state: present
    driver: macvlan
    driver_options:
      parent: eth0
    ipam_config:
      - subnet: "{{ router_subnet }}"
        gateway: "{{ router_gateway }}"
        iprange: "{{ ipv4_address }}/32" # Just reserve a single ip for the pihole

- name: "setup the pi-hole docker container"
  docker_container:
    name: "pihole"
    image: "pihole/pihole:latest"
    state: started
    restart: yes
    restart_policy: unless-stopped
    networks:
      - name: pihole
        ipv4_address: "{{ ipv4_address }}"
    volumes:
    - "/etc/pihole:/etc/pihole/"
    - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env:
      TZ: "{{ tz }}"
      WEBPASSWORD: "homelab"
    capabilities: NET_ADMIN
    dns_servers:
    - "127.0.0.1"
    - "8.8.8.8"
    - "1.1.1.1"
